version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: reachinbox-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - reachinbox-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: reachinbox-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - reachinbox-network

  qdrant:
    image: qdrant/qdrant
    container_name: reachinbox-qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - reachinbox-network

  app:
    build: .
    container_name: reachinbox-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=emails
      - OPENAI_API_KEY=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
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=email-vectors
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/demo/webhook/url
      - WEBHOOK_URL=https://webhook.site/demo-webhook-id
      - JWT_SECRET=demo-jwt-secret-key
      - LOG_LEVEL=info
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_SECURE=true
      - EMAIL_ACCOUNTS=user1@gmail.com,user2@outlook.com
      - EMAIL_PASSWORDS=password1,password2
    depends_on:
      - elasticsearch
      - qdrant
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - reachinbox-network

volumes:
  elasticsearch_data:
  qdrant_storage:

networks:
  reachinbox-network:
    driver: bridge
